redis:
  image: redis
  container_name: LogAlert-redis
  restart: always
  ports:
    - 6379:6379
  volumes:
    - ~/redis_LogAlert/data:/data
  command: redis-server --appendonly yes --requirepass "redis"